server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  
  cloud:
    gateway:
      routes:
        # Auth Service Route (No JWT filter needed here so you can log in)
        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
            
        # Product Service Route
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
          filters:
            - name: JwtAuth  # Ensure your Java class is named JwtAuthGatewayFilterFactory
            
        # Order Service Route
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - name: JwtAuth

# Custom Security Properties
security:
  jwt:
    secret: "5367566B5970337336763979244226452948404D635166546A576E5A71347437"
    expiration: 3600000

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
