server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
          filters:
            - JwtAuthFilter

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - JwtAuthFilter




