server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
            
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
          filters:
            - JwtAuth
            
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - JwtAuth

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
