server:
  port: 8080

spring:
  application:
    name: api-gateway
    
  # Cloud and Gateway Configuration
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
          filters:
            - name: JwtAuthFilterFactory

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - name: JwtAuthFilterFactory

  # Data and Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
